# Generated by Django 6.1 on 2026-10-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftresponse',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='shiftresponse',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
