# Generated by Django 6.1 on 2026-10-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_shiftresponse_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='shift',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
